export const USER_FORM_STRUCTURE = [
    {
        name: 'name',
        label: 'User Name',
        type: 'text',
        key: 'name',
        required: true,
        value: '',
        errors: '',
    },
    {
        name: 'phoneNumber',
        label: 'Phone Number',
        type: 'phonenumber',
        key: 'phoneNumber',
        required: true,
        value: {
            countryCode: 'IN',
            phoneNumber: '',
        },
        errors: '',
        maxLength: 10,
    },
    {
        name: 'alternateNumber',
        label: 'Alternate Number',
        type: 'phonenumber',
        key: 'alternateNumber',
        required: true,
        value: {
            alternateCountryCode: 'IN',
            alternateNumber: '',
        },
        errors: '',
        maxLength: 10,
    },
    {
        name: 'email',
        label: 'Email',
        type: 'text',
        key: 'email',
        required: true,
        value: '',
        errors: '',
        keyboardType: 'email-address',
        autoCapitalize: 'none',
        autoCorrect: false,
    },
    {
        name: 'address',
        label: 'Address',
        type: 'text',
        key: 'address',
        required: true,
        value: '',
        errors: '',
    },
    // add there address fields
    {
        type: 'twoColumn',
        key: 'countryState',
        component: [
            {
                name: 'country',
                label: 'Country',
                type: 'countrySelection',
                key: 'country',
                required: true,
                value: 'IN',
                errors: '',
                readonly: true,
            },
            {
                name: 'state',
                label: 'State',
                key: 'state',
                required: true,
                type: 'stateSelection',
                value: '',
                errors: '',
                readonly: true,
            },
        ],
    },
    {
        type: 'twoColumn',
        key: 'cityPincode',
        component: [
            {
                name: 'city',
                label: 'City',
                key: 'city',
                required: true,
                type: 'citySelection',
                value: '',
                errors: '',
            },
            {
                name: 'pincode',
                label: 'Pincode',
                type: 'number',
                key: 'pincode',
                required: true,
                value: '',
                errors: '',
                maxLength: 6,
            },
        ],
    },
    {
        name: 'imei1',
        label: 'IMEI 1',
        type: 'barcode',
        key: 'imei1',
        required: true,
        readonly: false,
        iconReadonly: false,
        value: '',
        errors: '',
    },
    {
        name: 'imei2',
        label: 'IMEI 2',
        type: 'barcode',
        key: 'imei2',
        required: true,
        readonly: false,
        iconReadonly: false,
        value: '',
        errors: '',
    },
    {
        name: 'model_number',
        label: 'Model Number',
        type: 'text',
        key: 'model_number',
        required: true,
        readonly: false,
        value: '',
        errors: '',
    },
    {
        type: 'twoColumn',
        key: 'keyTypeLoanCreatedDate',
        component: [
            {
                name: 'keytype',
                label: 'Key Type',
                type: 'dropdown',
                key: 'keytype',
                options: [],
                required: true,
                multiple: false,
                search: true,
                listModal: 'MODAL',
                apiDetails: { key: 'keytype' },
                value: '',
                errors: '',
                data: null
            },
            {
                name: 'emiDate',
                label: 'EMI Date',
                type: 'date',
                key: 'emiDate',
                required: false,
                value: Math.floor(Date.now() / 1000),
                errors: '',
                minDate: new Date(),
                maxDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
            },
        ],
    },
    {
        name: 'loanByCompany',
        label: 'Loan by Company Name',
        type: 'dropdown',
        options: [],
        key: 'loanByCompany',
        required: true,
        multiple: false,
        listModal: 'MODAL',
        search: true,
        apiDetails: {
            key: 'ledger',
        },
        value: '',
        errors: '',
    },
    {
        type: 'twoColumn',
        key: 'actualAndDownPayment',
        component: [
            {
                name: 'actualPrice',
                label: 'Actual Price',
                type: 'number',
                key: 'actualPrice',
                required: true,
                value: '',
                errors: '',
            },
            {
                name: 'prepaidPrice',
                label: 'Down Payment',
                type: 'number',
                key: 'prepaidPrice',
                required: true,
                value: '',
                errors: '',
            },
        ],
    },
    {
        name: 'installmentType',
        label: 'Installment Type',
        type: 'dropdown',
        options: [
            { value: 'daily', label: 'Daily' },
            { value: 'weekly', label: 'Weekly' },
            { value: 'monthly', label: 'Monthly' },
            { value: 'yearly', label: 'Yearly' },
        ],
        key: 'installmentType',
        required: true,
        multiple: false,
        value: '',
        errors: '',
    },
    {
        name: 'noOfEmis',
        label: 'Number of Installment',
        type: 'number',
        key: 'noOfEmis',
        required: true,
        value: '',
        errors: '',
        showIcon: true,
    },
    {
        key: 'photoLibrary',
        type: 'twoColumn',
        component: [
            {
                name: 'customerPhoto',
                label: 'Customer',
                type: 'file',
                accept: 'image/*',
                key: 'customerPhoto',
                required: true,
                value: '',
                errors: '',
                width: '90%',
                height: 70,
            },
            {
                name: 'idProof1Photo',
                label: 'ID Proof 1',
                type: 'file',
                accept: 'image/*',
                key: 'idProof1Photo',
                required: true,
                value: '',
                errors: '',
                width: '90%',
                height: 70,
            },
            {
                name: 'idProof2Photo',
                label: 'ID Proof 2',
                type: 'file',
                accept: 'image/*',
                key: 'idProof2Photo',
                required: true,
                value: '',
                errors: '',
                width: '90%',
                height: 70,
            },
        ],
    },
    {
        name: 'signature',
        label: 'Signature',
        type: 'signaturePad',
        key: 'signature',
        required: true,
        value: '',
        errors: '',
    },
    {
        name: 'termsAndConditions',
        label: 'Check Terms and Conditions',
        type: 'checkbox',
        key: 'termsAndConditions',
        required: true,
        value: '',
        errors: '',
    },
];

export const USER_FILE_FORM = [
    {
        type: "twoColumn",
        key: "countryState",
        component: [
            {
                name: "country",
                label: "Country",
                type: "countrySelection",
                key: "country",
                required: true,
                value: "",
                errors: ""
            },
            {
                name: "state",
                label: "State",
                key: "state",
                required: true,
                type: "stateSelection",
                value: "",
                errors: ""
            },

        ]
    },
    {
        type: "twoColumn",
        key: "cityPincode",
        component: [
            {
                name: "city",
                label: "City",
                key: "city",
                required: true,
                type: "citySelection",
                value: "",
                errors: ""
            },
            {
                name: "pincode",
                label: "Pincode",
                type: "number",
                key: "pincode",
                required: true,
                value: "",
                errors: ""
            },

        ]
    },
    // {
    //     name: "loanByCompany",
    //     label: "Loan by Company Name",
    //     type: "dropdown",
    //     options: [],
    //     key: "loanByCompany",
    //     required: true,
    //     multiple: false,
    //     listModal: "MODAL",
    //     search: true,
    //     apiDetails: { key: "ledger" },
    //     value: "",
    //     errors: ""
    // },
    // {
    //     type: "twoColumn",
    //     key: "keyTypeLoanCreatedDate",
    //     component: [
    //         {
    //             name: "keyType",
    //             label: "Key Type",
    //             type: "dropdown",
    //             key: "keyType",
    //             options: [],
    //             search: true,
    //             listModal: "MODAL",
    //             required: true,
    //             multiple: false,
    //             apiDetails: { key: "keyType" },
    //             value: "",
    //             errors: ""
    //         },
    //         {
    //             name: "emiDate",
    //             label: "EMI Date",
    //             type: "date",
    //             key: "emiDate",
    //             required: true,
    //             value: "",
    //             errors: ""
    //         },
    //     ]
    // },
    // {
    //     name: "installmentType",
    //     label: "Installment Type",
    //     type: "dropdown",
    //     options: [
    //         { value: "daily", label: "Daily" },
    //         { value: "weekly", label: "Weekly" },
    //         { value: "monthly", label: "Monthly" },
    //         { value: "yearly", label: "Yearly" },
    //     ],
    //     key: "installmentType",
    //     required: true,
    //     multiple: false,
    //     value: "",
    //     errors: ""
    // },
]